In [11]:
!pip install timesynth

In [66]:
import numpy as np
import matplotlib.pyplot as plt
import os
import plotly.express as px
import plotly.io as pio
pio.templates.default = "plotly_white"
import TimeSynth.timesynth as ts
import pandas as pd
np.random.seed()

# Data Generating Process and Time Series

In [13]:
def plot_time_series(time, values, label, legends=None):
    if legends is not None:
        assert len(legends)==len(values)
    if isinstance(values, list):
        series_dict = {"Time": time}
        for v, l in zip(values, legends):
            series_dict[l] = v
        plot_df = pd.DataFrame(series_dict)
        plot_df = pd.melt(plot_df,id_vars="Time",var_name="ts", value_name="Value")
    else:
        series_dict = {"Time": time, "Value": values, "ts":""}
        plot_df = pd.DataFrame(series_dict)

    if isinstance(values, list):
        fig = px.line(plot_df, x="Time", y="Value", line_dash="ts")
    else:
        fig = px.line(plot_df, x="Time", y="Value")
    fig.update_layout(
        autosize=False,
        width=900,
        height=500,
        title={
        'text': label,
#         'y':0.9,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top'},
        titlefont={
            "size": 25
        },
        yaxis=dict(
            title_text="Value",
            titlefont=dict(size=12),
        ),
        xaxis=dict(
            title_text="Time",
            titlefont=dict(size=12),
        )
    )
    return fig

def generate_timeseries(signal, noise=None):
    time_sampler = ts.TimeSampler(stop_time=20)
    regular_time_samples = time_sampler.sample_regular_time(num_points=100)
    timeseries = ts.TimeSeries(signal_generator=signal, noise_generator=noise)
    samples, signals, errors = timeseries.sample(regular_time_samples)
    return samples, regular_time_samples, signals, errors

os.makedirs("imgs/chapter_1", exist_ok=True)

In [5]:
def generate_timeseries(signal, noise=None):
  time_sampler = ts.TimeSampler(stop_time=20)
  regular_time_samples = time_sampler.sample_regular_time(num_points=100)
  timeseries = ts.TimeSeries(signal_generator=signal, noise_generator=noise)
  samples, signals, errors = timeseries.sample(regular_time_samples)
  return samples, regular_time_samples, signals, errors

In [16]:
os.makedirs("img/chapter_1", exist_ok=True)

In [14]:
# Generate the time axis with sequential numbers of 200
time = np.arange(200)
# Sample 200 random values
values = np.random.randn(200) * 100
type(values)

numpy.ndarray

In [15]:
!pip install kaleido

In [16]:
fig = plot_time_series(time, values, "")
fig.write_image('img/chapter_1/white_noise_processing.png')
fig.show()

# Red Noise

$x_{j+1} = r.x_{j} + \sqrt(1-r^2) . w$

In [17]:
# Setting the correlation coefficient
r = 0.4
# Generate the time axis
time = np.arange(200)
# Generate white noise
white_noise = np.random.randn(200) * 100
# Create Red Noise by introducing correlation between
# subsequent values in the white noise
values = np.zeros(200)
for i, v in enumerate(white_noise):
  if i == 0:
    values[i] = v
  else:
    values[i] = r * values[i-1] + np.sqrt((1-np.power(r, 2))) * v


In [21]:
np.sqrt(1-np.power(0.4, 2))

0.916515138991168

In [18]:
plot_time_series(time, values, "Red Noise Process")

## Cyclical or Seasonal Signals

In [53]:
# Sinusodial Signal with Amplitude=1.5 & Frequency=0.25
signal_1 = ts.signals.Sinusoidal(amplitude=1.5, frequency=0.25)
# Sinusodial Signal with Amplitude=1 & Frequency=0.5
signal_2 = ts.signals.Sinusoidal(amplitude=1, frequency=0.5)
# Generating the time series
samples_1 , regular_time_samples, signals_1, error_1 = generate_timeseries(signal=signal_1)
samples_2 , regular_time_samples, signals_2, error_2 = generate_timeseries(signal=signal_2)

plot_time_series(regular_time_samples, [samples_1, samples_2], "Sinosoidal Waves", legends=["Amplitude = 1.5 | Frequency = 0.25", "Amplitude = 1 | Frequency = 0.5"])

In [22]:
ts.TimeSampler(stop_time=20)

In [26]:
time_sampler = ts.TimeSampler(stop_time=20)

In [27]:
regular_time_samples = time_sampler.sample_regular_time(num_points=100)

In [28]:
regular_time_samples

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

In [29]:
len(regular_time_samples)

100

In [67]:
signal_1 = ts.signals.Sinusoidal(amplitude=1.5, frequency=0.25)
print(signal_1)

In [46]:
timeseries = ts.TimeSeries(signal_generator=signal_1)

In [47]:
timeseries

In [48]:
samples, signals, errors = timeseries.sample(regular_time_samples)

In [49]:
samples

array([ 0.00000000e+00,  4.68050169e-01,  8.89361894e-01,  1.22186393e+00,
        1.43235336e+00,  1.49981119e+00,  1.41750123e+00,  1.19364276e+00,
        8.50589796e-01,  4.22598835e-01, -4.75919002e-02, -5.13030215e-01,
       -9.27238479e-01, -1.24885478e+00, -1.44576324e+00, -1.49830101e+00,
       -1.40122179e+00, -1.16421970e+00, -8.10961226e-01, -3.76721981e-01,
        9.51358795e-02,  5.57493683e-01,  9.64181415e-01,  1.27458814e+00,
        1.45771735e+00,  1.49528216e+00,  1.38353144e+00,  1.13362436e+00,
        7.70516087e-01,  3.30465799e-01, -1.42584065e-01, -6.01395803e-01,
       -1.00015350e+00, -1.29903811e+00, -1.46820367e+00, -1.49075770e+00,
       -1.36444799e+00, -1.10188756e+00, -7.29295104e-01, -2.83876867e-01,
        1.89888680e-01,  6.44692368e-01,  1.03511852e+00,  1.32218005e+00,
        1.47721163e+00,  1.48473216e+00,  1.34399066e+00,  1.06904126e+00,
        6.87339783e-01,  2.37002094e-01, -2.37002094e-01, -6.87339783e-01,
       -1.06904126e+00, -

In [50]:
signals

array([ 0.00000000e+00,  4.68050169e-01,  8.89361894e-01,  1.22186393e+00,
        1.43235336e+00,  1.49981119e+00,  1.41750123e+00,  1.19364276e+00,
        8.50589796e-01,  4.22598835e-01, -4.75919002e-02, -5.13030215e-01,
       -9.27238479e-01, -1.24885478e+00, -1.44576324e+00, -1.49830101e+00,
       -1.40122179e+00, -1.16421970e+00, -8.10961226e-01, -3.76721981e-01,
        9.51358795e-02,  5.57493683e-01,  9.64181415e-01,  1.27458814e+00,
        1.45771735e+00,  1.49528216e+00,  1.38353144e+00,  1.13362436e+00,
        7.70516087e-01,  3.30465799e-01, -1.42584065e-01, -6.01395803e-01,
       -1.00015350e+00, -1.29903811e+00, -1.46820367e+00, -1.49075770e+00,
       -1.36444799e+00, -1.10188756e+00, -7.29295104e-01, -2.83876867e-01,
        1.89888680e-01,  6.44692368e-01,  1.03511852e+00,  1.32218005e+00,
        1.47721163e+00,  1.48473216e+00,  1.34399066e+00,  1.06904126e+00,
        6.87339783e-01,  2.37002094e-01, -2.37002094e-01, -6.87339783e-01,
       -1.06904126e+00, -

In [51]:
errors

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [57]:
# PseudoPeriodic Signal with Amplitude=1 & Frequency=0.25
signal = ts.signals.PseudoPeriodic(amplitude=1, frequency=0.25)

# Generating Timeseries
samples, regular_time_samples, signals, errors = generate_timeseries(signal=signal)
plot_time_series(regular_time_samples, samples, "PseudoPeriodic")

## AutoRegressive Signals

In [58]:
# Autoregressive signal with parameters 1.5 and -0.75
# y(t) = 1.5 * y(t-1) - 0.75 * y(t-2)
signal = ts.signals.AutoRegressive(ar_param=[1.5, -0.75])

In [59]:
# Generate TimeSeries
samples, regular_time_samples, signals, errors = generate_timeseries(signal=signal)
plot_time_series(regular_time_samples, samples, "Auto Regressive")

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:86: VisibleDeprecationWarning:

Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.



## Mix and Match

In [61]:
# Generating Pseudo Periodic Signal
pseudo_samples, regular_time_samples, _, _ = generate_timeseries(signal=ts.signals.PseudoPeriodic(amplitude=1, frequency=1), noise=ts.noise.GaussianNoise(std=0.3))
# Generating an Autoregressive Signal
ar_samples, regular_time_samples, _, _ = generate_timeseries(signal=ts.signals.AutoRegressive(ar_param=[1.5, -0.75]))
# Combining the two signals using a mathematical equation
ts = pseudo_samples *2 + ar_samples
plot_time_series(regular_time_samples, ts, "Pseudo Periodic with AutoRegression and White Noise")

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:86: VisibleDeprecationWarning:

Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.



# Stationary and Non-Stationary Time Series

## Non-Stationary Time Series

In [68]:
# Sinsoidal Signal with Amplitude=1 & Frequency=0.25
signal = ts.signals.Sinusoidal(amplitude=1, frequency=0.25)

# White noise with standard deviation = 0.3
noise = ts.noise.GaussianNoise(std=0.3)

# Generate the time series
sinusoidal_samples, regular_time_samples, _, _ = generate_timeseries(signal=signal, noise=noise)

# # Regular_time_samples is a linear increasing time axis and can be used as a trend
trend = regular_time_samples * 0.4

# Combining the signal and trend
ts = sinusoidal_samples + trend
plot_time_series(regular_time_samples, ts, "Sinusoidal with Trend and White Noise")